version: "3.9"
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: muser
      MINIO_ROOT_PASSWORD: mpassword
    command: server --console-address ":9001" /data

volumes:
  minio_storage: 
    name: minio_storage